In [ ]:
%pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [ ]:
x = [1, 2, 3, 4, 5]
series_x = pd.Series(x) # PascalCase
series_x

arr_x = np.array(x)
# arr_x
series_x = pd.Series(arr_x)
series_x[0]
series_x[1:3]
series_x[::-1] # 뒤집기 (reverse)
series_x[series_x > 3]

3    4
4    5
dtype: int64

In [24]:
series_x + 1
series_x * 10
series_x + series_x

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [25]:
series_x.index

RangeIndex(start=0, stop=5, step=1)

In [26]:
series_x.values

array([1, 2, 3, 4, 5])

In [ ]:
sr_x = pd.Series(x, index=['a', 'b', 'c', 'd', 'e'])
sr_x.index
# sr_x.values

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
sr_x['b']
# []를 통한 묵시적 인덱스 접근은 3.0.5버전에서 제외됨
sr_x[ ['b', 'c'] ] # 팬시 색인

sr_x[ sr_x > 2 ]

sr_x.a # 인덱스명을 속성으로 취급하여 가져오는 방법 (잘 안씀)

np.int64(1)

In [ ]:
x = {'수학': 90, '영어': 80, '과학': 95, '미술': 80}
sr_x = pd.Series(x)
sr_x['영어':'과학'] # 시작과 끝값이 포함이 됨

영어    80
과학    95
dtype: int64

In [47]:
x = {'수학': 90, '영어': 80, '과학': 95, '미술': 80}
sr_x = pd.Series(x, index=['수학', '과학'])
sr_x

수학    90
과학    95
dtype: int64

In [48]:
student_1 = {'수학': 90, '영어': 80, '과학': 95, '미술': 80} # 홍길동
student_2 = {'수학': 70, '영어': 90, '과학': 100, '미술': 70} # 이몽룡

In [56]:
index_1 = ['홍길동'] * 4 + ['이몽룡'] * 4
            # ['홍길동' for _ in range(4)] + ['이몽룡' for _ in range(4)]
index_2 = list(student_1.keys()) + list(student_2.keys())
            # [key for key in student_1] + [key for key in student_2]
index_1, index_2

values_all = list(student_1.values()) + list(student_2.values())
values_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [57]:
sr_scores = pd.Series(values_all, index=[index_1, index_2])
sr_scores

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [69]:
x = [1, None, 2, None, 3, 4, None]
y = pd.Series(x)

y

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [70]:
y.sum(), y.min(), y.max()

(np.float64(10.0), np.float64(1.0), np.float64(4.0))

In [74]:
y.isnull().sum()

np.int64(3)

In [75]:
y.dropna()

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [76]:
y.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [94]:
x = pd.Series([1, 2, 3, 4])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])

In [97]:
# 
sr_xyz = pd.concat([x, y, z], axis=1, join='inner', ignore_index=True) # verify_integrity=True
sr_xyz

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [101]:
x % 2

0    1
1    0
2    1
3    0
dtype: int64

In [ ]:
x.describe() # 기초통계, 데이터 살펴보기

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [103]:
x.head(2)

0    1
1    2
dtype: int64

In [104]:
x.tail(2)

2    3
3    4
dtype: int64

### 실습 01

In [ ]:
np.random.seed(5)
x = [np.nan, 1, 2, 3, 4, 5]
y = pd.Series([x[np.random.randint(0,6)] for i in range(20)])
y

In [ ]:
# 결측값의 개수
y.isnull().sum()
# y.count() # == notnull().sum()

np.int64(5)

In [ ]:
drop_y = y.dropna(ignore_index=True)
drop_y

In [ ]:
mean_y = y.mean()
mean_y

fill_y = y.fillna(mean_y)
fill_y

In [115]:
sales_data = {
    '연도' : [2015, 2016, 2017, 2018, 2019, 2020],
    '판매량' : [103, 70, 130, 160, 190, 230],
    '매출' : [500000, 300000, 400000, 550000, 700000, 680000],
    '순이익' : [370000, 190000, 300000, 480000, 600000, 590000]
}

sales_df = pd.DataFrame(sales_data)
sales_df

     연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [119]:
sales_df['판매량']

0    103
1     70
2    130
3    160
4    190
5    230
Name: 판매량, dtype: int64

In [123]:
sales_df.iloc[3]

연도       2018
판매량       160
매출     550000
순이익    480000
Name: 3, dtype: int64

In [124]:
pd.DataFrame(sales_data, columns=['판매량', '매출', '순이익'], index=sales_data['연도'])

      판매량      매출     순이익
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [126]:
sales_df.set_index('연도')

      판매량      매출     순이익
연도
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [147]:
sales_df.reset_index().to_csv('sales_data2.csv', index=None, encoding='cp949')

In [135]:
sales_df = pd.read_csv('sales_data.csv', header=0, index_col=0, encoding='utf-8')

In [137]:
sales_df.to_csv('sales_data2.csv', encoding='cp949')

In [149]:
# 
pd.read_csv('sales_data2.csv', header=0, index_col=0, encoding='cp949')

      판매량      매출     순이익
연도
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [150]:
sales_data = {
    '연도':[2015, 2016, 2017, 2018, 2019, 2020],
    '판매량':[103, 70, 130, 160, 190, 230],
    '매출':[500000, 300000, 400000, 550000, 700000, 680000],
    '순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}

sales_df = pd.DataFrame(sales_data)

In [153]:
sales_df['순이익률'] = sales_df['순이익'] / sales_df['매출'] * 100
sales_df

     연도  판매량      매출     순이익       순이익률
0  2015  103  500000  370000  74.000000
1  2016   70  300000  190000  63.333333
2  2017  130  400000  300000  75.000000
3  2018  160  550000  480000  87.272727
4  2019  190  700000  600000  85.714286
5  2020  230  680000  590000  86.764706

In [ ]:
def check(n):
    if n > 80:
        return '높음'
    else:
        return '낮음'

def check(n):
    return '높음' if n > 80 else '낮음'

In [158]:
sales_df['순이익률_비교'] = sales_df['순이익률'].apply(lambda x: '높음' if x > 80 else '낮음')
# lambda는 map, filter에서 주로 활용
sales_df

     연도  판매량      매출     순이익       순이익률 순이익률_비교
0  2015  103  500000  370000  74.000000      낮음
1  2016   70  300000  190000  63.333333      낮음
2  2017  130  400000  300000  75.000000      낮음
3  2018  160  550000  480000  87.272727      높음
4  2019  190  700000  600000  85.714286      높음
5  2020  230  680000  590000  86.764706      높음

In [162]:
# 1. boolean values
bool_indexes = (sales_df['순이익률_비교'] == '높음') & (sales_df['순이익'] > 550000)

# 2. indexing
sales_df[ bool_indexes ]

     연도  판매량      매출     순이익       순이익률 순이익률_비교
4  2019  190  700000  600000  85.714286      높음
5  2020  230  680000  590000  86.764706      높음

In [167]:
sales_df['테스트'] = sales_df[bool_indexes]['매출'] - 5000

In [168]:
sales_df

     연도  판매량      매출     순이익       순이익률 순이익률_비교       테스트
0  2015  103  500000  370000  74.000000      낮음       NaN
1  2016   70  300000  190000  63.333333      낮음       NaN
2  2017  130  400000  300000  75.000000      낮음       NaN
3  2018  160  550000  480000  87.272727      높음       NaN
4  2019  190  700000  600000  85.714286      높음  695000.0
5  2020  230  680000  590000  86.764706      높음  675000.0

In [172]:
df = pd.read_csv('sales_data2.csv', header=0, encoding='cp949')

# len(df)
df.loc[6] = [2021, 250, 720000, 620000]
df

     연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000
6  2021  250  720000  620000

In [ ]:
for i in range(len(df)):
    print( df.iloc[i] )

In [ ]:
df['테스트1'] = 'test1'
df['테스트2'] = 'test2'
df['테스트3'] = 'test3'
df

In [ ]:
del df['테스트1']
df

In [ ]:
# axis=1 -> 열 삭제
df.drop(['테스트2'], axis=1, inplace=True) # df

In [184]:
# axis=0 -> 행 삭제, 기본값 = 0
df.drop([4, 5], )
df

     연도  판매량      매출     순이익   테스트3
0  2015  103  500000  370000  test3
1  2016   70  300000  190000  test3
2  2017  130  400000  300000  test3
3  2018  160  550000  480000  test3
4  2019  190  700000  600000  test3
5  2020  230  680000  590000  test3
6  2021  250  720000  620000  test3

In [191]:
# sales_data.drop(sales_data.columns[[0, 2]], axis='columns', inplace=True)

df.drop(df.columns[ [0, 2] ], axis=1, inplace=True)

In [192]:
df

      순이익
0  370000
1  190000
2  300000
3  480000
4  600000
5  590000
6  620000

In [199]:
df = pd.DataFrame(
    np.random.randint(1, 100, size=(4, 4)),
    index=[['A', 'A', 'B', 'B'],['a', 'b', 'a', 'b']],
    columns=[['가가','가가','나나','나나'],['가','나','가','나']]
)
df[ ('가가', '나') ]

# df.loc['A']

df.index
df.columns

MultiIndex([('가가', '가'),
            ('가가', '나'),
            ('나나', '가'),
            ('나나', '나')],
           )

In [ ]:
df = pd.DataFrame(
    np.random.randint(1, 100, size=(8, 2)),
    index=[
        ['A창고','A창고','A창고','A창고','B창고','B창고','B창고','B창고'],
        ['사과','배','바나나','사과','사과','배','바나나','배']
    ],
    columns=['판매','재고']
)

df.index.names = ['창고명','상품명']

         판매  재고
창고명 상품명
A창고 사과   16  23
    배    71  10
    바나나  64  95
    사과   15  67
B창고 사과   58  20
    배    65   9
    바나나   9  72
    배    13  21

In [202]:
df.groupby('창고명').sum()

      판매   재고
창고명
A창고  166  195
B창고  145  122

In [203]:
df.groupby('상품명').sum()

      판매   재고
상품명
바나나   73  167
배    149   40
사과    89  110

In [204]:
df.groupby(['창고명', '상품명']).sum()

         판매  재고
창고명 상품명
A창고 바나나  64  95
    배    71  10
    사과   31  90
B창고 바나나   9  72
    배    78  30
    사과   58  20

In [207]:
df.sort_values(['판매'], ascending=False).head(3)

         판매  재고
창고명 상품명
A창고 배    71  10
B창고 배    65   9
A창고 바나나  64  95

In [209]:
df.sort_values(['판매', '재고'], ascending=[True, False])

         판매  재고
창고명 상품명
B창고 바나나   9  72
    배    13  21
A창고 사과   15  67
    사과   16  23
B창고 사과   58  20
A창고 바나나  64  95
B창고 배    65   9
A창고 배    71  10

## 실습 02

In [ ]:
np.random.seed(5)
df = pd.DataFrame(
    np.random.randint(1, 100, size=(15, 3)),
    index=[
        # [f'{i}학년' for i in range(1, 4) for _ in range(5)], # 학년
        ['1학년'] * 5 + ['2학년'] * 5 + ['3학년'] * 5,
        # [f'{i}반' for _ in range(3) for i in range(1, 6) ]  # 반
        [f'{i}반' for i in range(1, 6)] * 3
    ],
    columns=['국어', '영어', '과학'],
)
df

In [259]:
subject_cols = ['국어', '영어', '과학']
df['합계'] = df[subject_cols].sum(axis=1)
df['평균'] = df['합계'] / len(subject_cols)
df

        국어  영어  과학   합계         평균
1학년 1반  79  62  17  158  52.666667
    2반  74   9  63  146  48.666667
    3반  28  31  81  140  46.666667
    4반   8  77  16  101  33.666667
    5반  54  81  28  163  54.333333
2학년 1반  45  78  76  199  66.333333
    2반  66  48  31  145  48.333333
    3반  85  87  19  191  63.666667
    4반  10  42  63  115  38.333333
    5반   2  83  17  102  34.000000
3학년 1반  79   6  59  144  48.000000
    2반   1  81   5   87  29.000000
    3반  37  52  28  117  39.000000
    4반  32   3  69  104  34.666667
    5반  39  84  20  143  47.666667

In [265]:
df.index.names = ['학년', '반']
df.groupby('학년').sum()

      국어   영어   과학   합계          평균
학년
1학년  243  260  205  708  236.000000
2학년  208  338  206  752  250.666667
3학년  188  226  181  595  198.333333

### 실습 03

In [267]:
df = pd.read_csv('titanic.csv')

In [273]:
print(len(df))
df.describe() # include 옵션: O - object만, all - 전체

891

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# 1. 결측지 처리를 해주세요. 
# (age - 평균값적용, Cabin - N으로, Embarked-N)

In [277]:
# ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
# 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

df.head(2).T

,0,1
PassengerId,1,2
Survived,0,1
Pclass,3,1
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th..."
Sex,male,female
Age,22.0,38.0
SibSp,1,1
Parch,0,0
Ticket,A/5 21171,PC 17599
Fare,7.25,71.2833
Cabin,NaN,C85
Embarked,S,C

In [282]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [283]:
df['Age'].isnull().sum()

np.int64(0)

In [ ]:
df['Cabin'].isnull().sum() # 687
df['Embarked'].isnull().sum() # 2

np.int64(2)

In [288]:
df['Cabin'] = df['Cabin'].fillna('N')
df['Embarked'] = df['Embarked'].fillna('N')

In [ ]:
df['Cabin'].isnull().sum() # 0
df['Embarked'].isnull().sum() # 0

np.int64(0)

In [ ]:
# 2. 성(Sex)별 생존자 합을 구해주세요

In [292]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
# df[['Sex', 'Survived']]

df.groupby('Sex').sum()['Survived']

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
# 3. 클래스(Pclass)별 생존자 합을 구해주세요

In [299]:
df[['Pclass', 'Survived']]

df.groupby('Pclass').sum()['Survived']

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [304]:
# 4. 나이(Age)를 활용 유아, 10대, 20대, 30대, 40대, 50대, 60대, 노인의 생존자 합을 구해주세요.

def get_group(age):
    if age < 10:
        return '유아'
        
    for i in range(1, 7):
        if age//10 == i :
            return f'{i}0대'
    
    return '노인'
    # if age < 10:
    #     return '유아'
    # elif age < 20:
    #     return '10대'
    # ...
    # elif age < 70:
    #     return '60대'
    # else:
    #     return '노인'

df['Age_group'] = df['Age'].apply(get_group)
df.groupby('Age_group').sum()['Survived']

Age_group
10대     41
20대    129
30대     73
40대     34
50대     20
60대      6
노인       1
유아      38
Name: Survived, dtype: int64